### PR TITLE
adding dependant packages to setup.py

### LINKED ISSUE #7: Add dependencies in `setup.py`

### PR DESCRIPTION
**Pull request by sculley**
Updating `setup.py` to install the dependant package `numpy` as part of the install process.

Fixes #7

### CODE REVIEW

**Comment by sculley** [comment]
I have installed and tested the package locally using

```shell
pip install .
```

I can confirm `numpy` is installed as part of the installation process.

**Comment by sculley** [comment]
I forgot to add `pandas` to the list in `setup.py`, the new commit addresses this.

**Comment by sculley** [comment]
I squashed all commits into one fyi

**Comment by pberkes** [comment]
LGTM, thank you

**Pull request merged**
